version: '3.8'

services:
  backend-service:
    image: objectorienters/techspot_backend
    depends_on:
      database-service:
        condition: service_healthy
    environment:
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DATABASE: oop
      MYSQL_HOST: database-service
    ports:
      - "8080:8080"
    networks:
      - my-network

  database-service:
    image: objectorienters/techspot_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: oop


    networks:
      - my-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]

      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 0s

  phymyadmin:
    image: phpmyadmin
    ports:
      - "80:80"
    depends_on:
      database-service:
        condition: service_healthy
    environment:
      PMA_HOST: database-service
      MYSQL_ROOT_PASSWORD:
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

